### ISSUE TITLE
Unable to build in VS 2019 16.0.0

### ISSUE THREAD

**Issue by IoTFier** [dotnet-architecture/eShopOnContainers#996]
Hi,

I am not able to build the solution eShopOnContainers in VS2019 16.0.0
My environment - Win 10 64 Oct 2018 with latest cumulative pack.
H/W - Surface Book 2 16gb ram SSD. [unfortunately windows Hyper-V team has blocked access to the dGPU causing that GPU sit idle in 99 % of my use during development work]  

Building using docker compose didn't work against the copy of the cloned code.

In the interest of upgrading the mobile app to XF 3.6 latest version, I upgraded all available stable NuGet packages across projects in this entire solution. With the upgrade of Polly to 7.1, I was hutting two errors in the Marketing API / MarketingConextSeed.cs file. In its constructor policy.ExecuteAsync is not supported any more and in CreatePolicy method Policy.Handle returns type was having a mismatch. 

As a result, I reverted back the Polly version to 6.0.1.

After that building of the solution using docker-compose is failing with errors -
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0006	Metadata file '{local repo path}\eShopOnContainers\src\Services\Ordering\Ordering.Infrastructure\bin\Debug\netstandard2.0\Ordering.Infrastructure.dll' could not be found	Ordering.API	{local repo path}\eShopOnContainers\src\Services\Ordering\Ordering.API\CSC	1	Active
Error	CS0535	'OrderingContextDesignFactory.NoMediator' does not implement interface member 'IMediator.Publish(object, CancellationToken)'	Ordering.Infrastructure	{local repo path}\eShopOnContainers\src\Services\Ordering\Ordering.Infrastructure\OrderingContext.cs	133	Active
Error	MSB3030	Could not copy the file "{local repo path}\eShopOnContainers\src\Services\Basket\Basket.API\bin\Debug\netcoreapp2.2\Basket.API.dll" because it was not found.	docker-compose	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets	4374	
Error	MSB3030	Could not copy the file "{local repo path}\eShopOnContainers\src\Services\Ordering\Ordering.API\bin\Debug\netcoreapp2.2\Ordering.API.dll" because it was not found.	docker-compose	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets	4374	

Your help will be appreciated.

Thanks

**Comment by mvelosop** [comment]
Hi @IoTFier,

There seems to be some leftovers from previous compilations. and I'm guessing you followed the setup guide: https://github.com/dotnet-architecture/eShopOnContainers/wiki#setting-up-your-development-environment-for-eshoponcontainers

Anyway you should also:

- Delete all **bin** and **obj** folders in the projects
- Clear VS component cache (https://github.com/Codealike/Codealike-KnowledgeBase/blob/master/clear-visual-studio-component-cache.md)
- Reset Docker (and the computer as well, why not? 😉)

You could also try building from the CLI

Hope this helps.

**Comment by IoTFier** [comment]
Hi @mvelosop,
I am trying to follow the set up guide as per that link .. but stuck with broken compilation even before I set up firewall rules. 

- I, respectfully, disagree with the recommendation of resetting docker and computer as I have other things working fine. 
- I will try clear VS component cache.
- I tried doing a build via CLI docker-build also failed for the same reasons. 
      - Are there any specific documented steps that I should follow ?
- Will there be an update with Polly v7.x?
 
Please help me get this compiled and running on my PC. 
It is a great reference solution and architecture. 
I am looking forward to learn from such a wonder work done by your team's contribution.

Thanks

**Comment by mvelosop** [comment]
Hi @IoTFier,

The app usually builds fine so let's try to find out what's happening in your environment.

I think I read too fast over your question. Upgrading all packages in the solution to latest stable versions is probably not a good idea, so it's be better to go step by step.

One benefit from a microservices architecture is that you should be able to upgrade projects independently.

Before anything else let's try building an unmodified commit.

Commit 6396e0ffbe53555d1d1b03bf6a1bac2bd6d80cac from 03-APR-2019 builds just fine with SDK  2.2.202.

You can check latest installed SDK with

```console
dotnet --version
```
You should get something like this, being the last one the most recent:

![image](https://user-images.githubusercontent.com/7357806/55739143-64511700-5a20-11e9-83aa-36905a690fc3.png)

I'd also try building with the CLI first.

**Comment by mvelosop** [comment]
Closing this issue now, but feel free to comment, will reopen if needed.
